# This code was automatically generated by CWrap version 0.0.0

cdef extern from "common.h":

    void git_libgit2_version(int *major, int *minor, int *rev)

    cdef enum:
        GIT_CAP_THREADS
        GIT_CAP_HTTPS

    int git_libgit2_capabilities()

    cdef enum:
        GIT_OPT_GET_MWINDOW_SIZE
        GIT_OPT_SET_MWINDOW_SIZE
        GIT_OPT_GET_MWINDOW_MAPPED_LIMIT
        GIT_OPT_SET_MWINDOW_MAPPED_LIMIT

    void git_libgit2_opts(int option)


