# This code was automatically generated by CWrap version 0.0.0

cdef extern from "cred_helpers.h":

    cdef struct git_cred_userpass_payload:
        char *username
        char *password

    ctypedef git_cred_userpass_payload git_cred_userpass_payload

    int git_cred_userpass(git_cred **cred, char *url, char *user_from_url, unsigned int allowed_types, void *payload)


