# This code was automatically generated by CWrap version 0.0.0

cdef extern from "git2.h":

    int git_graph_ahead_behind(size_t *ahead, size_t *behind, git_repository *repo, git_oid *one, git_oid *two)
