# This code was automatically generated by CWrap version 0.0.0

cdef extern from "net.h":

    cdef enum git_direction:
        GIT_DIRECTION_FETCH
        GIT_DIRECTION_PUSH

    cdef struct git_remote_head:
        int local
        git_oid oid
        git_oid loid
        char *name

    ctypedef int (*git_headlist_cb)(git_remote_head *, void *)


