# This code was automatically generated by CWrap version 0.0.0

cdef extern from "signature.h":

    int git_signature_new(git_signature **out, char *name, char *email, git_time_t time, int offset)

    int git_signature_now(git_signature **out, char *name, char *email)

    git_signature *git_signature_dup(git_signature *sig)

    void git_signature_free(git_signature *sig)


