# This code was automatically generated by CWrap version 0.0.0

cdef extern from "trace.h":

    cdef enum git_trace_level_t:
        GIT_TRACE_NONE
        GIT_TRACE_FATAL
        GIT_TRACE_ERROR
        GIT_TRACE_WARN
        GIT_TRACE_INFO
        GIT_TRACE_DEBUG
        GIT_TRACE_TRACE

    ctypedef void (*git_trace_callback)(git_trace_level_t, char *)

    int git_trace_set(git_trace_level_t level, git_trace_callback cb)
