GIT_OBJ_COMMIT = None
Signature = None
GIT_DIFF_INCLUDE_UNMODIFIED = None
GitError = None
GIT_REF_OID = None
GIT_REF_SYMBOLIC = None
GIT_OBJ_ANY = None
GIT_OBJ_BLOB = None
GIT_OBJ_COMMIT = None
init_repository = None
discover_repository = None
Commit = None
hashfile = None
GIT_SORT_TIME = None
GIT_SORT_REVERSE = None


GIT_STATUS_CURRENT = 0
GIT_STATUS_INDEX_DELETED = 0
GIT_STATUS_INDEX_MODIFIED = 0
GIT_STATUS_INDEX_NEW = 0
GIT_STATUS_WT_DELETED = 0
GIT_STATUS_WT_MODIFIED = 0
GIT_STATUS_WT_NEW = 0
