# This code was automatically generated by CWrap version 0.0.0

cdef extern from "git2.h":

    int git_ignore_add_rule(git_repository *repo, char *rules)

    int git_ignore_clear_internal_rules(git_repository *repo)

    int git_ignore_path_is_ignored(int *ignored, git_repository *repo, char *path)
