# This code was automatically generated by CWrap version 0.0.0

cdef extern from "git2.h":

    git_reference *git_reference__alloc(git_refdb *refdb, char *name, git_oid *oid, char *symbolic)

    int git_refdb_new(git_refdb **out, git_repository *repo)

    int git_refdb_open(git_refdb **out, git_repository *repo)

    int git_refdb_compress(git_refdb *refdb)

    void git_refdb_free(git_refdb *refdb)

    int git_refdb_set_backend(git_refdb *refdb, git_refdb_backend *backend)
