# This code was automatically generated by CWrap version 0.0.0

cdef extern from "git2.h":

    cdef enum git_reset_t:
        GIT_RESET_SOFT
        GIT_RESET_MIXED
        GIT_RESET_HARD

    int git_reset(git_repository *repo, git_object *target, git_reset_t reset_type)

    int git_reset_default(git_repository *repo, git_object *target, git_strarray *pathspecs)
